openacid/celeritasdb

.travis.yml
Cargo.toml
components/hello/Cargo.toml
components/hello/src/lib.rs
components/hello/tests/hello.rs
src/main.rs

hello world

---

components/epaxos/src/command/command.rs
components/epaxos/src/command/mod.rs
components/epaxos/src/command/tests/command_tests.rs
components/epaxos/src/instance/instance.rs
components/epaxos/src/instance/mod.rs
components/epaxos/src/instance/tests/instance_tests.rs
components/epaxos/src/lib.rs
components/epaxos/src/replica/mod.rs
components/epaxos/src/replica/replica.rs
components/epaxos/src/replica/tests/replica_tests.rs

command, instance data type and ut structure

---

components/epaxos/src/command/mod.rs
components/epaxos/src/conf/conf.rs
components/epaxos/src/conf/mod.rs
components/epaxos/src/conf/tests/conf_tests.rs
components/epaxos/src/instance/instance.rs
components/epaxos/src/instance/mod.rs
components/epaxos/src/lib.rs
components/epaxos/src/message/message.rs
components/epaxos/src/message/mod.rs
components/epaxos/src/message/tests/message_tests.rs
components/epaxos/src/replica/mod.rs
components/epaxos/src/replica/replica.rs

conf, message, replica basic data type

data type: conf, message, replica

---

components/epaxos/Cargo.toml
components/epaxos/src/conf/conf.rs
components/epaxos/src/lib.rs
components/epaxos/src/snapshot/errors.rs
components/epaxos/src/snapshot/mod.rs
components/epaxos/src/snapshot/rocks/dbutil.rs
components/epaxos/src/snapshot/rocks/mod.rs

增加了 snapshot module
**本次 review 的功能**：
- 打开一个 rocksdb

init mod snapshot and some interfaces

---

components/epaxos/src/snapshot/enum_str.rs
components/epaxos/src/snapshot/mod.rs
components/epaxos/src/snapshot/rocks/mod.rs

用宏定义重构 snapshot 里的2个 enum.
Fixes #32

refactor enum definition in snapshot use macro!

---

Cargo.toml
components/cele_threads/Cargo.toml
components/cele_threads/README.md
components/cele_threads/src/cele_threads.rs
components/cele_threads/src/lib.rs

公共thread pool 封装。
提供简单接口，提供trait以及错误类型。
方便换库。
Fixes # (issue)
New feature

cele_threads: simple thread pool API interface of threads_pool

---

docs/snapshot/README.md

snapshot add a document

---

.travis.yml
Cargo.toml
src/bin/cele.rs
tests/support/mod.rs
tests/test_setget.rs

- Copy server startup code from redis-rs.
- Add naive command line argument parse.

Ci test server

---

Cargo.toml
src/bin/cele.rs

use crate clap to parse command line argument

---

components/epaxos/src/data/instance.rs
components/epaxos/src/data/protos/instance.proto
components/epaxos/src/instance/instance.rs
components/epaxos/src/instance/tests/instance_tests.rs

new instance data structure
Fixes # (issue)
- **New feature**     
- **Breaking change** 

new instance data structure

---

components/epaxos/src/snapshot/mod.rs
components/epaxos/src/snapshot/traits.rs
docs/snapshot/README.md

把 snapshot 会对外提供的几块接口定义成为 trait。
顺便小调整了下之前的设计文档。
- **New feature**     

define traits of snapshot

---

components/epaxos/src/replica/exec.rs
components/epaxos/src/replica/mod.rs

epaxos execution graph dfs

---

components/epaxos/src/data/README.md
components/epaxos/src/data/instance.rs
components/epaxos/src/data/protos/instance.proto
wiki/replication-algo.md

rename accepted_deps to final_deps. Accept or Commit sets this field

---

Makefile
tests/support/mod.rs
tests/test_setget.rs
wiki/Discussion.md
wiki/Epaxos-execution.md
wiki/Get-rid-of-seq.md
wiki/Home.md
wiki/Makefile
wiki/Reduce-SCC-to-avoid-livelock.md
wiki/_Sidebar.md
wiki/proof-same-view.md
wiki/replication-algo.md

format .rs and .md

---

components/epaxos/src/snapshot/mod.rs
components/epaxos/src/snapshot/rocks/dbutil.rs
components/epaxos/src/snapshot/rocks/mod.rs

删除了默认的几个 rocksdb path，改为由使用者指定一个位置。
删除了测试产生的 test.db 临时文件。
Fixes #78 

to remove tmp testdb

---

src/bin/cele.rs

Just refactor before adding new replication-server

refactor server, sepearte listener and server-loop

---

.travis.yml
components/hello/src/lib.rs
src/bin/cele.rs
tests/support/mod.rs
tests/test_setget.rs

启动另外一个端口(默认6666) 接受replication protocol的请求.
还没有实现. 现在模拟redis protocol做一个简单测试.

replication server draft impl

---

components/epaxos/src/data/protos/message.proto
wiki/replication-algo.md

- Use a Request struct and a Reply struct for all communication.
In a message, use req_type to identify request type such as PreAccept
etc.
- Clarify the fields required by different message, both in comment and wiki.
proto对应的rs文件没有更新, 会乱, 等pr过了再更.

simplify message definition.

---

components/epaxos/src/message/message.rs
components/epaxos/src/message/tests/message_tests.rs

fix typo: Commit should be Prepare; add test of Request and Reply

---

.gitpod.yml
components/epaxos/src/command/command.rs
components/epaxos/src/command/tests/command_tests.rs
components/epaxos/src/instance/instance.rs
components/epaxos/src/instance/tests/instance_tests.rs
components/epaxos/src/message/tests/message_tests.rs

rename XXX:new_xxx() to XXX:of(), for making a new struct with specified fields

---

components/epaxos/src/data/message.rs
components/epaxos/src/data/protos/message.proto
components/epaxos/src/message/message.rs
components/epaxos/src/message/tests/message_tests.rs
components/epaxos/src/replica/replica.rs

remove struct Message. remove make_xxx_req. use Request::xxx instead.

---

components/epaxos/src/command/command.rs
components/epaxos/src/instance/instance.rs
components/epaxos/src/message/message.rs

refine message struct init

---

components/epaxos/src/instance/instance.rs
components/epaxos/src/instance/tests/instance_tests.rs
components/epaxos/src/lib.rs
components/epaxos/src/tokey.rs

To simplify key generating for underlying storage

feat: add trait ToKey to InstanceID and Instance

---

components/epaxos/src/snapshot/mod.rs
components/epaxos/src/snapshot/rocks/dbutil.rs
components/epaxos/src/snapshot/rocks/engine.rs
components/epaxos/src/snapshot/rocks/mod.rs

1. snapshot.Engine 改名为 RocksEngine ；
2. 实现几个操作 rocksdb 的基本函数；
3. 调整目录结构；
- **New feature**     

rename snapshot Engine to RocksEngine; and implements base function.

---

components/epaxos/src/instance/instance.rs
components/epaxos/src/snapshot/errors.rs
components/epaxos/src/snapshot/iters.rs
components/epaxos/src/snapshot/memEngine/memdb.rs
components/epaxos/src/snapshot/memEngine/mod.rs
components/epaxos/src/snapshot/mod.rs
components/epaxos/src/snapshot/rocks/engine.rs
components/epaxos/src/snapshot/traits.rs

mock mem_engine issue:#80

---

wiki/protobuf.md

doc: add rust protobuf related crate relationship

---

components/epaxos/src/snapshot/rocksEngine/engine.rs

改进 rocksEngine set 和 mset 的参数，把 columnfamily，key，value 包装成一个结构体。

refactery: use a struct in rocksEngine.set/mset

---

components/epaxos/src/snapshot/enum_str.rs
components/epaxos/src/snapshot/rocksEngine/engine.rs

feature: impl From for CfKV

---

components/epaxos/src/replica/errors.rs
components/epaxos/src/replica/mod.rs

replica add errors mod

---

components/epaxos/src/instance/mod.rs
components/epaxos/src/instance/tests/instance_tests.rs

impl instance after function

---

components/epaxos/src/replica/replica.rs

replica add snapshot engion, exec variables

---

components/epaxos/src/command/tests/command_tests.rs
components/epaxos/src/instance/tests/instance_tests.rs
components/epaxos/src/lib.rs
components/epaxos/src/message/tests/message_tests.rs
components/epaxos/src/testutil.rs

refactor: simplify test with macro

---

Cargo.toml
src/bin/cele.rs
tests/test_setget.rs

测试中启动一个server, 监听2个端口: redis api的和replication的,然后分别连接了1下.

feat: rewrite server with async network

---

components/epaxos/src/message/mod.rs
components/epaxos/src/message/tests/message_tests.rs
components/epaxos/src/protos/message.proto
components/epaxos/src/protos/qpaxos.proto
components/epaxos/src/protos/saved.proto
components/epaxos/src/qpaxos/mod.rs
components/epaxos/src/replica/replica.rs
components/epaxos/tests/test_repl_server.rs
tests/test_setget.rs

Seperate `Request` into 4 concrete request so that error checking would
be easier.
Create 4 corresponding grpc APIs.

feat: individual request: fast_accept, accept, commit, prepare.

---

components/epaxos/src/replica/exec.rs
components/epaxos/src/replica/mod.rs
components/epaxos/src/replica/replica.rs
components/epaxos/src/replica/tests/exec_tests.rs

replica exec impl execute commands and instances

---

components/epaxos/src/snapshot/iters.rs
components/epaxos/src/snapshot/traits.rs

- add unit test for InstanceIter

unittest for InstanceIter

---

components/epaxos/src/qpaxos/conflict.rs
components/epaxos/src/qpaxos/mod.rs
components/epaxos/src/qpaxos/test_command.rs
components/epaxos/src/snapshot/test_engine.rs

feat: Command::conflict to check if two command conflict

---

components/epaxos/src/replica/mod.rs
components/epaxos/src/replica/replica.rs
components/epaxos/src/replica/test_replica.rs
components/epaxos/src/replica/tests/replica_tests.rs

feat: add test to handle_commit_request

---

components/epaxos/src/snapshot/rocks_engine/engine.rs
components/epaxos/src/snapshot/rocks_engine/mod.rs
components/epaxos/src/snapshot/rocks_engine/test_engine.rs

snapshot.rocks_engine 实现 Base trait

rocks_engine impl snapshot.Base

---

components/epaxos/build.rs
components/epaxos/src/qpaxos/mod.rs
components/epaxos/src/replica/replica.rs
components/epaxos/src/replica/test_replica.rs
components/epaxos/src/snapshot/errors.rs
components/epaxos/src/snapshot/iters.rs
components/epaxos/src/snapshot/traits/test_base.rs

-   Improve InvalidRequest by impl `From<(&str, &str, &str)>` and
`From<(&str, &str)>`.
This would ease test writing.
-   InvalidRequest should always contains specific field path:
`to_replica_id -> cmn.to_replica_id`.
-   Add tests of InvalidRequest for commit and accept.
TODO: add the same tests to fast-accept and prepare.

add test of InvalidRequest for commit and accept.

---

components/epaxos/src/replica/test_replica.rs

test: add test of handle_accept_request

---

components/epaxos/src/replica/test_replica.rs

refactor: replica: use macro to simplify invalid request test

---

components/epaxos/src/snapshot/iters.rs
components/epaxos/src/snapshot/mem_engine/memdb.rs
components/epaxos/src/snapshot/rocks_engine/engine.rs
components/epaxos/src/snapshot/test_engine.rs
components/epaxos/src/snapshot/traits/traits.rs

instance and base iter support reverse mod

---

components/epaxos/build.rs
components/epaxos/src/qpaxos/macros.rs
components/epaxos/src/qpaxos/mod.rs
components/epaxos/src/qpaxos/test_command.rs
components/epaxos/src/qpaxos/test_instance.rs

`cmds![("Set", "key", "value"), (OpCode::Get, "a", "b")]`
`instids![(1, 2), (3i32, 4i64)]`
- **Breaking change**   

feat: add macro to simplify making Command and InstanceId

---

components/epaxos/src/lib.rs
components/epaxos/src/qpaxos/macros.rs
components/epaxos/src/qpaxos/mod.rs
components/epaxos/src/qpaxos/test_instance.rs
components/epaxos/src/replica/test_replica.rs

feat: add macro `inst!` to easily create an instance

---

components/epaxos/src/replica/replica.rs
components/epaxos/src/replica/test_replica.rs

test: add test of None fields for handle-fast-accept-request

---

components/epaxos/src/protos/instance.proto
components/epaxos/src/replica/mod.rs
components/epaxos/src/replica/replica.rs
components/epaxos/src/replica/status.rs
components/epaxos/src/replica/test_replica.rs
components/epaxos/src/replica/tests/exec_tests.rs

feat: handle accept reply

---

components/epaxos/src/qpaxos/macros.rs
components/epaxos/src/qpaxos/test_instance.rs
components/epaxos/src/replica/test_replica.rs

refactor: use macro to simplify instance creation for test

---

components/epaxos/src/snapshot/mem_engine/memdb.rs
components/epaxos/src/snapshot/mem_engine/mod.rs

refactor: use Arc<Mutex<BTreeMap>> to impl mem-engine

---

.travis.yml
components/epaxos/Cargo.toml
components/epaxos/src/qpaxos/macros.rs
components/epaxos/src/qpaxos/mod.rs
components/epaxos/src/qpaxos/test_macros.rs

Macor init inst

---

components/epaxos/src/replica/status.rs
components/epaxos/src/replica/test_status.rs

feat: add get_accept_dep() to find out what dep to use for accept

---

components/epaxos/src/replica/mod.rs
components/epaxos/src/replica/replica.rs
components/epaxos/src/replica/test_exec.rs
components/epaxos/src/replica/test_replica.rs
components/epaxos/src/replica/test_util.rs

feat: bcast request to other replica

---

components/epaxos/src/qpaxos/errors.rs
components/epaxos/src/qpaxos/test_errors.rs
components/epaxos/src/replica/replica.rs

ProtocolError::Incomplete

---

Cargo.toml
src/bin/cele.rs
tests/support/mod.rs

feat: use ClusterInfo to config the server

---

components/epaxos/src/conf/conf.rs
src/bin/cele.rs

refactor: add cluster into Server

---

components/epaxos/src/replica/status.rs
components/epaxos/src/replica/test_status.rs

fix: if fast-quorum is 0, then n==1. then fast-commit can always be done

---

components/epaxos/src/replica/status.rs
components/epaxos/src/replica/test_status.rs

feat: Status.get_accept_deps(): to get deps for accept-request

---

components/epaxos/src/replica/status.rs
components/epaxos/src/replica/test_status.rs

Get fast commit deps

---

Cargo.toml
components/epaxos/src/conf/conf.rs
components/epaxos/src/replica/test_replica.rs
components/epaxos/src/replica/test_status.rs
components/epaxos/src/replication/mod.rs
src/bin/cele.rs
src/errors.rs
src/lib.rs
src/serverdata.rs
src/test_serverdata.rs

Refactor server data

---

Cargo.toml
components/epaxos/Cargo.toml
components/epaxos/build.rs
components/epaxos/src/protos/command.proto
components/epaxos/src/replica/exec.rs
components/epaxos/src/replica/test_exec.rs
components/epaxos/src/snapshot/errors.rs
components/epaxos/src/snapshot/mem_engine/memdb.rs
components/epaxos/src/snapshot/rocks_engine/engine.rs
components/epaxos/src/snapshot/traits/traits.rs

exec replace transaction with write batch

---

components/epaxos/src/conf/conf.rs
components/epaxos/src/replica/errors.rs
components/epaxos/src/replica/exec.rs
components/epaxos/src/replica/replica.rs
components/epaxos/src/replica/test_replica.rs
components/epaxos/src/replica/test_util.rs
components/epaxos/src/serverdata/serverdata.rs
components/epaxos/src/snapshot/rocks_engine/engine.rs

Fixes #237 
formed a **self-review** of my own code

fix: finish new replica func

---

src/bin/cele.rs
src/lib.rs
src/redisapi/mod.rs
src/redisapi/redisapi.rs

refactor: move redis api impl into standalone file

---

src/bin/cele.rs
src/redisapi/redisapi.rs

feat: Server: add stop(), join() and impl Drop

---

src/bin/cele.rs
src/lib.rs
src/server/errors.rs
src/server/mod.rs
src/server/server.rs
tests/support/mod.rs
tests/test_setget.rs

In proc server

---

components/epaxos/src/lib.rs
components/epaxos/src/replica/test_replica.rs
components/epaxos/src/replication/errors.rs
components/epaxos/src/replication/mod.rs
components/epaxos/src/replication/replication.rs
src/redisapi/redisapi.rs
tests/test_setget.rs

Test only with "set" command on a single replica cluster.
No execution support yet.
No commit broadcasting yet.

feat: replication impl for a cluster of 1 member

---

components/epaxos/src/qpaxos/display.rs
components/epaxos/src/qpaxos/mod.rs
components/epaxos/src/qpaxos/test_display.rs

feat: impl Display for qpaxos data types

---

Cargo.toml
components/epaxos/Cargo.toml
components/epaxos/src/qpaxos/macros.rs
src/server/server.rs
tests/test_replica.rs

feat: add start replica exec thread

---

components/epaxos/src/qpaxos/display.rs
components/epaxos/src/qpaxos/test_display.rs

Display replicate request reply

---

components/epaxos/src/replica/exec.rs
components/epaxos/src/replica/replica.rs
components/epaxos/src/replica/test_exec.rs
components/epaxos/src/testutil.rs
src/server/server.rs

feat: replica exec send reply to client

---

Cargo.toml
components/epaxos/Cargo.toml
components/epaxos/src/lib.rs
components/epaxos/src/replica/exec.rs
src/bin/cele.rs
src/lib.rs
src/redisapi/redisapi.rs
src/server/server.rs
src/setup/mod.rs
src/setup/setup.rs

feat: add a global logger

---

Cargo.toml
src/lib.rs
src/setup/log_format.rs
src/setup/mod.rs
src/setup/setup.rs
src/setup/test_format.rs

feat: define log fromat

---

components/epaxos/src/replica/replica.rs
src/redisapi/redisapi.rs
src/server/server.rs
tests/test_setget.rs

broadcast commit message after set

broadcast commit message after set

---

components/storage/Cargo.toml
components/storage/src/rocks_engine/engine.rs

使用 rust-rocksdb 主线分支，解决 clang 编译出错的问题

storage: use rust-rocksdb master branch.
