openacid/celeritasdb

Cargo.toml, components/protobuf-gen-rust/Cargo.toml, components/protobuf-gen-rust/README.md, components/protobuf-gen-rust/src/main.rs, components/protobuf-gen-rust/test/protos/items/items.proto, components/protobuf-gen-rust/test/protos/upper_items.proto
rust 版本从.proto生成rs文件的工具。
```
└── test
├── dest
└── protos
├── items
│   └── items.proto
└── upper_items.proto
```
```
cargo run -- -o test/dest  -s test/protos
```
```
└── test
├── dest
│   ├── items
│   │   └── items.rs
│   └── upper_items.rs
└── protos
├── items
│   └── items.proto
└── upper_items.proto
```
=> rust protobuf tool

Cargo.toml, src/bin/cele.rs
adopt crate "redis" as protocol parser. Reponse serialization is still using "parse". Simplify protocol parsing.
=> use crate redis as protocol parser

components/epaxos/src/data/protos/instance.proto
It is quite easy to bind methods to `Vec[InstanceID]`,
thus there is no trouble operating instance-ids without introduce
another type.
InstIDs creates a wrapper type:
https://docs.rs/protobuf/2.0.0/protobuf/struct.RepeatedField.html
E.g.:
```
trait Has {
fn has(&self, i: i64) -> bool;
}
struct InstanceID {
v: i64,
}
impl Has for Vec<InstanceID> {
fn has(&self, i:i64) -> bool {
self[0].v == i
}
}
impl Has for [InstanceID] {
fn has(&self, i:i64) -> bool {
false
}
}
fn main() {
let a = vec![InstanceID{v:1}, InstanceID{v:2}];
println!("{}", a.has(2));
let b = &[InstanceID{v:1}, InstanceID{v:2}];
println!("{}", b.has(1));
}
```
=> remove InstIDs. use `repeat InstanceID` instead.

components/epaxos/src/data/protos/instance.proto, components/epaxos/src/data/protos/message.proto, components/epaxos/src/instance/instance.rs, components/epaxos/src/instance/tests/instance_tests.rs, components/epaxos/src/message/message.rs, components/epaxos/src/message/tests/message_tests.rs, components/epaxos/src/replica/replica.rs
- Use uniform field index.
- Rename Message.Request to Message.TypeRequest and so is
Message.TypeReply, for the upcoming Request and Reply message.
- Comment out several fields in struct Replica.
=> Pass test without inst ids

components/epaxos/src/command/command.rs, components/epaxos/src/command/tests/command_tests.rs, components/epaxos/src/data/command.rs, components/epaxos/src/data/message.rs, components/epaxos/src/data/protos/command.proto, components/epaxos/src/instance/tests/instance_tests.rs, components/epaxos/src/message/tests/message_tests.rs
change key value type from string to vector of u8. make it compatible with rocksdb APIFixes # (issue)
- **Breaking change**
=> change key value type from string to vector of u8. make it compatible with rocksdb API

components/epaxos/src/data/instance.rs, components/epaxos/src/data/message.rs, components/epaxos/src/data/protos/instance.proto, components/epaxos/src/data/protos/message.proto, components/epaxos/src/instance/instance.rs, components/epaxos/src/instance/tests/instance_tests.rs, components/epaxos/src/message/message.rs, components/epaxos/src/message/tests/message_tests.rs
An instance has several status thus one status field is not enough.
E.g. `a` could be Accepted but not Preaccepted
To determine the instance status:
- is-preaccepted:  if deps is not empty.
- is-accepted:     if final_deps is not empty and not Instace.committed
- is-committed:    if Instace.committed
- is-executed:     if Instance.executed
- **Breaking change**
=> replace Instance.status with "committed" and "executed"

components/epaxos/src/replica/exec.rs, components/epaxos/src/replica/replica.rs, components/epaxos/src/replica/tests/exec_tests.rs
R2自己认为R1上没有instance可以exec，实际上是可能有需要exec的instance，这个时候就需要recover R1上的instance，然后再exec。
例如在R2上看到的Instance Space如下：
```
R1          R2
-------------
|           |
d(NotFound) |
| ↖ ........b(Committed)
a(Executed) |
instances((a, d]) not exist in this replica, recover instance(a+1) first
```
- R1上没有instance可exec
- R2上找到一个b需要exec
- 由于b→d(not found in R1)
- 这个时候R1(a, d]这个区间的instances是缺失的
- recover R1(a+1)，然后再选择每个replica最小的instance执行
=> replica exec impl find missing instances

components/epaxos/Cargo.toml, components/epaxos/build.rs, components/epaxos/src/instance/mod.rs, components/epaxos/src/instance/tests/instance_tests.rs
- feat: add "dervie Copy" for basic types.
- feat: use derive_more to make creating struct more easily
- refactor: simplify instanceID test with into()
=> feat: derive Copy and From for simple datatypes

components/epaxos/build.rs, components/epaxos/src/protos/README.md, components/epaxos/src/qpaxos/mod.rs, components/epaxos/src/qpaxos/t.rs, components/epaxos/src/snapshot/memEngine/memdb.rs
- refactor: remove BallotNum::of. use auto-generated ::from instead
- fix: protos README.md
=> feat: generate PartialOrd etc, remove manually impl

components/epaxos/src/replica/exec.rs, components/epaxos/src/replica/tests/exec_tests.rs, components/epaxos/src/snapshot/mem_engine/memdb.rs, components/epaxos/src/snapshot/traits.rs
Rules:
-   If a function consumes a variable, it moves the var.
It is the caller's responsibility to clone it before re-using a var
after calling the function.
-   If a function does not consume a variable, the parameter should be
a reference to the var.
-   Fixed size var always pass value instead of reference for
simplicity, if there is not performance issue with it.
=> refactor: simplify reference usage

components/epaxos/Cargo.toml, components/epaxos/src/replica/exec.rs, components/epaxos/src/replica/replica.rs, components/epaxos/src/replica/tests/exec_tests.rs, components/epaxos/src/snapshot/iters.rs, components/epaxos/src/snapshot/mem_engine/memdb.rs, components/epaxos/src/snapshot/traits.rs
After adjust, the storage engine traits are:
-   trait Base: basice kv access.
-   trait TxEngine: transactional API, begin, commit etc.
-   trait StatusEngine: it is based on Base and TxEngine.
-   trait InstanceEngine: it is based on all these three, because updating
instance requires the status to be updated together.
Removed unnecessary generics:
-   `Replica<E> -> Replica`: `Replica does not need to be abstract. Only the
engine need to be abstract.
-   `InstanceIter<MemEngine> -> InstanceIter`: it does not need to know
the underlying engine type, it only needs to know the trait the
engine provides.
-   Moves `next_kv` to trait `Base`. Because scaning is a very basic
operation for a **basic** kv-storage.
Also a BaseIter is introduced for impl of iteration on trait Base.
- …
=> adjust engine traits

components/epaxos/Cargo.toml, components/epaxos/src/conf/conf.rs, components/epaxos/src/conf/errors.rs, components/epaxos/src/conf/mod.rs, components/epaxos/src/conf/tests/conf_tests.rs
parse cluster conf from yaml to ClusterInfo struct
Fixes # (https://github.com/openacid/celeritasdb/issues/110)
=> use rust yaml to parse cluster conf

.travis.yml, components/epaxos/src/replica/replica.rs, components/epaxos/src/snapshot/mem_engine/memdb.rs, components/epaxos/src/snapshot/traits.rs
Move unrelated functions into separate traits.
And in order to maximize sharing, I tried to move as much functionality as
possible from implementation into traits.
Storage engine traits layers:
`Base -> ObjectEngine -> ColumnedEngine -> StatusEngine -> InstanceEngine`
-   At the bottom level, it is `trait Base` which is a bytes oriented engine
and `trait TxEngine` which provides basic tx operation.
-   Upon `Base` it is `trait ObjectEngine`, which provides APIs to read/write rust
struct, the type of struct is specified by trait implementation.
In our impl, `Object` is set to `Instance`
-   Upon `ObjectEngine` it is `ColumnedEngine`.
It organizes object in columns and provides "reference" to track
objects in columns.
E.g. `get_ref("max", col_id)` to get max object id in column
`col_id`, …
=> Better trait

components/epaxos/src/replica/exec.rs, components/epaxos/src/replica/replica.rs, components/epaxos/src/snapshot/iters.rs, components/epaxos/src/snapshot/mem_engine/memdb.rs, components/epaxos/src/snapshot/mod.rs, components/epaxos/src/snapshot/test_engine.rs, components/epaxos/src/snapshot/traits.rs
-   Add contrains that ColumnId : Copy
-   Add `set_ref_if`: update ref only if provided condition satisfied.
-   Simplify `set_instance` with conditional setter: `set_ref_if`.
-   Add test of `set_instance`.
-   Remove StatusEngine. Use method from ColumnedEngine instead.
-   Follow the convention that pass parameter xxID as value, xx as
reference if it is not consumed.
-   Rename some local vars.
=> Rm status engine

components/epaxos/Cargo.toml, components/epaxos/build.rs, components/epaxos/src/qpaxos/mod.rs, components/epaxos/src/qpaxos/t.rs, components/epaxos/src/qpaxos/test_command.rs, components/epaxos/src/replica/exec.rs, components/epaxos/src/replica/replica.rs, components/epaxos/src/snapshot/iters.rs, components/epaxos/src/snapshot/mem_engine/memdb.rs, components/epaxos/src/snapshot/mod.rs, components/epaxos/src/snapshot/test_engine.rs, components/epaxos/src/snapshot/traits.rs
Derive `FromStr` impl for OpCode so that writing test is easier.
Add `From` to Command:
```
Command::from((OpCode::Set, "k", "v"));
// or
Command::from(("Set", "k", "v"));
// or just
("Set", "k", "v").into(); // if type can be inferred from context.
```
=> feat: use enum-utils to derive FromStr for enum type

components/epaxos/src/qpaxos/mod.rs, components/epaxos/src/replica/exec.rs, components/epaxos/src/replica/replica.rs, components/epaxos/src/replica/tests/exec_tests.rs, components/epaxos/src/snapshot/iters.rs, components/epaxos/src/snapshot/mem_engine/memdb.rs, components/epaxos/src/snapshot/test_engine.rs, components/epaxos/src/snapshot/traits.rs
- In order to distinguish not-found from other unhandlable error, result
is an Option<Instance> instead of Instance.
Add test of get_instance().
- Move replicaID into mod qpaxos, because it is a core concept for
replication.
- refactor: remove InstanceID::of, use ::from instead
=> refactor: get_instance() returns Result<Option<>, Err>

components/epaxos/src/replica/exec.rs, components/epaxos/src/snapshot/mem_engine/memdb.rs, components/epaxos/src/snapshot/test_engine.rs, components/epaxos/src/snapshot/traits.rs
- next_instance_id() incr "max" ref and return the next available instance id.
- Remove update_instance(). Use set_instance() instead.
=> feat: add next_instance_id()

.travis.yml, components/epaxos/src/replica/exec.rs, components/epaxos/src/snapshot/iters.rs, components/epaxos/src/snapshot/mem_engine/memdb.rs, components/epaxos/src/snapshot/test_engine.rs, components/epaxos/src/snapshot/traits.rs
set_instance() should not update "max" ref. "max" ref should only be
updated by next_instance_id().
set_instance() do not need arg instance_id.
- **Breaking change**
=> Set instance without instance id

components/epaxos/src/qpaxos/mod.rs, components/epaxos/src/qpaxos/t.rs, components/epaxos/src/qpaxos/test_instance.rs, components/epaxos/src/snapshot/iters.rs, components/epaxos/src/snapshot/mem_engine/memdb.rs, components/epaxos/src/snapshot/test_engine.rs
=> feat: Instance::conflict() to check if two instance contains conflicting commands

components/epaxos/src/snapshot/iters.rs, components/epaxos/src/snapshot/mem_engine/memdb.rs, components/epaxos/src/snapshot/traits.rs
- InstanceIter should use InstanceEngine instead of Base.
- InstanceIter should use instanceID as cursor type, instead of ReplicaID.
get_instance_iter() should accept a `include` arg.
- Add error handling to InstanceIter. Also complete tests.
- **Breaking change**   
=> fix: InstanceIter

components/epaxos/build.rs, components/epaxos/src/protos/errors.proto, components/epaxos/src/protos/message.proto, components/epaxos/src/qpaxos/mod.rs, components/epaxos/src/qpaxos/t.rs, components/epaxos/src/replica/replica.rs
- Add proto errors to define errors for qpaxos protocol.
- Add MakeReply::err_common() to add field cmn containing an error.
Fixes #134 
- **Breaking change**
=> feat: impl handle-commit-request

components/epaxos/src/snapshot/mem_engine/memdb.rs, components/epaxos/src/snapshot/mod.rs, components/epaxos/src/snapshot/traits/mod.rs, components/epaxos/src/snapshot/traits/test_base.rs, components/epaxos/src/snapshot/traits/traits.rs
调整测试文件的结构：
1.  traits.rs -> traits/traits.rs;
2. test_engine.rs -> traits/test_base.rs;
3. 在 mem_engine/ 的测试里调用 traits/test_base 对各个 traits 接口的测试；
=> 调整 snapshot traits 的测试结构

components/epaxos/src/protos/errors.proto, components/epaxos/src/qpaxos/t.rs, components/epaxos/src/replica/replica.rs, components/epaxos/src/snapshot/errors.rs
-   Add qpaxos proto error InvalidRequest to respond a request error.
-   Add two snapshot errors as func return value.
-   Add internal error to qpaxos proto error converter: Error::to_qerr().
=> feat: add error InvalidRequest; convert Error for transport

components/epaxos/src/protos/message.proto, components/epaxos/src/qpaxos/mod.rs, components/epaxos/src/qpaxos/t.rs, components/epaxos/src/replica/replica.rs, components/epaxos/src/replica/test_replica.rs, components/epaxos/tests/test_repl_server.rs, tests/test_setget.rs
-   proto: move err out of ReplyCommon, as a standalone field in XXXReply.
-   Remove MakeRequest::err_common().
-   MakeRequest add arg to_replica_id to specify where to send.
-   Simpilfy handle_xxx() error handling with Error::to_qerror().
-   Impl handle_accept(), without test yet. TODO
-   Add request check.
=> refactor: simplify handle_commit

components/epaxos/src/snapshot/mem_engine/memdb.rs, components/epaxos/src/snapshot/rocks_engine/test_engine.rs, components/epaxos/src/snapshot/traits/test_base.rs
把 mem_engine 的测试移到了 traits/test_base 里，用来测试多个 engine 的实现。
=> refactery: move mem_engine/tests to traits/test_base

components/epaxos/src/snapshot/mod.rs, components/epaxos/src/snapshot/rocks_engine/test_engine.rs, components/epaxos/src/snapshot/test_engine.rs, components/epaxos/src/snapshot/traits/mod.rs
Rename:
Before: snapshot/traits/test_base.rs
After : snapshot/test_engine.rs
`test_base.rs` actually test all engine trait, not only the `Base`
trait, and it is not test for trait but for trait impl.
=> refactor: epaxos: adjust test file locations

components/epaxos/src/protos/instance.proto, components/epaxos/src/qpaxos/mod.rs, components/epaxos/src/qpaxos/test_instance.rs
-   InstanceIdVec impl trait Deref thus it can be used the same way as
with `Vec<InstanceId>`.
-   InstanceIdVec also impl trait Index, to get InstanceId by ReplicaID
just like accessing a Vec: `instance_id_vec[replica_id]`.
It panics if specified replica id not found, just like accessing an
absent key on a BTreeMap.
-   InstanceIdVec provides a `get(rid: ReplicaID)` method to safely get
an `Option<InstanceID>`.
=> feat: add InstanceIdVec as wrapper of Vec<InstanceId>

components/epaxos/src/replica/replica.rs, components/epaxos/src/replica/test_replica.rs, components/epaxos/src/snapshot/errors.rs
=> implement fast-accept handler

components/epaxos/build.rs, components/epaxos/src/qpaxos/mod.rs, components/epaxos/src/qpaxos/test_instance.rs
- `From<Vec<InstanceID>>`
- `From<&[InstanceID]>>`
- `From<[({int}, {int})]>>` requires {int} to be a type that can be converted into ReplicaID and i64.
- `From<&[({int}, {int})]>>`
- From empty array/slice
- From array or ref of array with length 1~8.
=> feat: InstanceIdVec: add a lot From<...> impl

components/epaxos/src/protos/instance.proto, components/epaxos/src/protos/message.proto, components/epaxos/src/qpaxos/mod.rs, components/epaxos/src/qpaxos/t.rs, components/epaxos/src/qpaxos/test_instance.rs, components/epaxos/src/replica/exec.rs, components/epaxos/src/replica/replica.rs, components/epaxos/src/replica/test_replica.rs, components/epaxos/src/replica/tests/exec_tests.rs, components/epaxos/src/snapshot/test_engine.rs
=> Use instanceIdVec

components/epaxos/src/qpaxos/mod.rs, components/epaxos/src/qpaxos/test_instance.rs, components/epaxos/src/replica/replica.rs
- Add InstanceIdVec::set() to add or replace instance-id by replica_id;
- Add PartialOrd impl to compare with an InstanceId
=> Set inst id vec

components/epaxos/src/replica/exec.rs, components/epaxos/src/replica/replica.rs, components/epaxos/src/replica/test_exec.rs, components/epaxos/src/replica/test_replica.rs, components/epaxos/src/snapshot/mem_engine/memdb.rs, components/epaxos/src/snapshot/rocks_engine/engine.rs, components/epaxos/src/snapshot/traits/traits.rs
-   Engine does not need a `mut` ref to work. All `&mut self` are
changed to `&self`. It is the reponsibility of the Engine to deal
with data modification.
In our case, RocksEngine calls underlying C-API to modify data,
MemEngine uses a Mutex to protect the underlying BTreeMap.
-   Define a type `Storage` which is an Arc of a trait object.
-   Testing: every file use its own resource creation utilities.
A test should better not rely on another test.
Prefer duplication than generalization for tests.
Fix: #132
=> replica::new_instance

components/epaxos/src/replica/replica.rs, components/epaxos/src/replica/test_replica.rs
=> fix: quorum() gives wrong result when n=2k

components/epaxos/src/qpaxos/mod.rs, components/epaxos/src/qpaxos/quorums.rs, components/epaxos/src/qpaxos/test_quorums.rs, components/epaxos/src/replica/replica.rs
Calculating quorum number should not a task of a replica.
=> feat: add qpaxos::quorums.rs to calculate quorum number.

.travis.yml, components/epaxos/src/qpaxos/errors.rs, components/epaxos/src/qpaxos/mod.rs, components/epaxos/src/qpaxos/test_errors.rs
-   Move protocol error into qpaxos::errors::ProtocolError:
NoSuchReplica, LackOf.
-   Define `Into<QError>` to replace to_qerr().
=> feat: add qpaxos::errors

.travis.yml, components/epaxos/build.rs, components/epaxos/src/replica/errors.rs, components/epaxos/src/replica/replica.rs, components/epaxos/src/replica/test_replica.rs, components/epaxos/src/snapshot/errors.rs
```
ReplicaError  ----------------into-+-> QError
|                               |
+ wrap --> ProtocolError --into-'
+ wrap --> SnapError(storage error)
- -------> other replica error
```
-   travis: fix: use nightly rustfmt to make tonic-build happy.
-   ReplicaError wraps ProtocolError and Storage error.
Then it is easier to transfer error between functions.
-   Impl conversion from errors to QError with `Into<QError>`, instead
of to_qerr().
-   Refactor: use specific error name such ReplicaError, ProtocolError
etc.
=> Replica error

components/epaxos/src/replica/replica.rs, components/epaxos/src/replica/status.rs, components/epaxos/src/replica/test_replica.rs
-   Add all neccessary fields(fast-fields, accept-fields) to `Status`.
-   `Status` now has an reference to the `instance` it replicates for.
-   Add duplicated message check to handle_accept_reply().
-   Add safe ballot compare without using `unwrap()`.
=> refactor: use one Status to track all phases: fast, accept, prepare etc.

components/epaxos/build.rs, components/epaxos/src/lib.rs, components/epaxos/src/qpaxos/errors.rs, components/epaxos/src/replica/errors.rs, components/epaxos/src/replica/replica.rs, components/epaxos/src/replica/status.rs, components/epaxos/src/replication/errors.rs, components/epaxos/src/replication/hdlreply.rs, components/epaxos/src/replication/mod.rs, components/epaxos/src/replication/test_hdlreply.rs, components/epaxos/src/snapshot/errors.rs
-   Refactor: add Eq impl to errors.
-   Feature: define replication::HandlerError as enum of all errors
occurs during handling requests/replies.
-   Add handle_fast_accept_reply().
fix: #176 
=> feat: mod replication impl replication algo.

components/epaxos/src/replica/status.rs, components/epaxos/src/replica/test_replica.rs, components/epaxos/src/replica/test_status.rs, components/epaxos/src/replication/test_hdlreply.rs
-   When Status::new(), it initiate accept_ok to 0, until
Status::start_accept() is called.
-   Add Status::start_fast_accept() to initiate Status with initial
deps.
-   Test Status::new()
=> test: add test of Status::new()

components/epaxos/src/conf/conf.rs, components/epaxos/src/conf/errors.rs, components/epaxos/src/conf/tests/conf_tests.rs
-   node_id is set to the key of a node in clusterinfo.
-   And node id as an optional replication address.
-   Refine ConfError: from 3 error:std::io::Error when reading yaml.
serde_yaml::Error when parsing yaml and from a malformed replication
addr.
-   Deref ClusterInfo into ClusterInfo.nodes thus it is much easier to
use.
=> refactor: conf: make node id.

components/epaxos/src/conf/conf.rs, components/epaxos/src/conf/errors.rs, components/epaxos/src/conf/tests/conf_tests.rs
-   feat: cluster conf yaml now requires an `replicas` dict field.
-   feat: `get_replica_node() -> &Node` to find what node a replica is.
-   feat: add `check_replicas` to ensure that there is no replica in
conf is assigned to a absent node.
-   refactor: dep: use crate tempfile to make a temp file: easy to cleanup.
=> feat: Cluster add replica-to-node-id mapping.

components/epaxos/src/conf/conf.rs, components/epaxos/src/conf/errors.rs, components/epaxos/src/conf/tests/conf_tests.rs, tests/support/mod.rs
=> feat: ClusterInfo need to track key-range to group mapping

components/epaxos/src/replica/status.rs, components/epaxos/src/replica/test_status.rs, components/epaxos/src/replication/hdlreply.rs, components/epaxos/src/replication/test_hdlreply.rs
There is an issue of rust: a fake modify-a-borrowed problem:
```rust
struct Inst { a: i32, }
struct St<'a> { inst: &'a Inst, }
fn borrow_it(s: &mut St) { }
fn main() {
let mut i = Inst{a:3};
let mut s = St{ inst: &i, };
i.a = 5;
borrow_it(&mut s);
}
```
```
error[E0506]: cannot assign to `i.a` because it is borrowed
--> refmut.rs:16:5
|
14 |         inst: &i,
|               -- borrow of `i.a` occurs here
15 |     };
16 |     i.a = 5;
|     ^^^^^^^ assignment to borrowed `i.a` occurs here
17 |     borrow_it(&mut s);
|               ------ borrow later used here
error: aborting due to previous error
```
- **Breaking change**   
=> change: Status now has an instance in it instead of a reference

components/epaxos/src/snapshot/traits/traits.rs, src/bin/cele.rs, tests/support/mod.rs
-   feat: CeleServer as server level error type.
TODO: take a better name for it.
-   feat: Server should be able to be cloned and shared across
coroutines. Thus core data is put into a Arc<ServerData> struct.
-   feat: Server::new() takes a parameter Storage.
-   feat: Server initialize cluster info, replcias etc.
-   refactor: extract protocol impl out of server. Adds RedisApi
struct.
=> feat: server: add clusterconf to specify a cluster it serves for.

components/epaxos/src/conf/conf.rs, components/epaxos/src/conf/tests/conf_tests.rs, src/bin/cele.rs
=> Improve server

components/epaxos/src/replica/exec.rs, components/epaxos/src/replica/test_replica.rs, components/epaxos/src/snapshot/iters.rs, components/epaxos/src/snapshot/mem_engine/memdb.rs, components/epaxos/src/snapshot/mem_engine/mod.rs, components/epaxos/src/snapshot/rocks_engine/engine.rs, components/epaxos/src/snapshot/rocks_engine/mod.rs, components/epaxos/src/snapshot/rocks_engine/test_engine.rs, components/epaxos/src/snapshot/test_engine.rs, components/epaxos/src/snapshot/traits/traits.rs
- mem和rocks仅需要实现底层base接口，其他trait 接口公用
- ref、kv、instance保存在不同的cf中，避免key相同相互覆盖
- 删除OjbectEngine trait，逻辑挪到InstanceEngine，现在来看它是多余的，只有InstanceEngine用到了它
- InstanceEngine、ColumnedEngine中所有接口参数均改为固定类型。目前来看并不需要他们支持设置参数类型
- rocks engine已经可以使用，所有接口都已完成。
=> mem and rocks use same public trait, kv/instance/ref use diff cf

Cargo.toml, components/epaxos/src/service/service.rs, src/bin/cele.rs
- replication impl MyQPaxos adds a new method get_replica() to get replica from request.
=> Server improve

components/epaxos/src/replica/replica.rs, components/epaxos/src/replica/test_replica.rs
Do not rely on get_ref(max...) to get the max instance id.
Thus in future ref "max" can be removed.
=> refactor: new_instance() should store the created instance in storage.

components/epaxos/src/replica/replica.rs, components/epaxos/src/replica/status.rs, components/epaxos/src/replica/test_replica.rs, components/epaxos/src/replica/test_status.rs, components/epaxos/src/replication/errors.rs, components/epaxos/src/replication/hdlreply.rs, components/epaxos/src/replication/test_hdlreply.rs
=> Refine handlers

components/epaxos/src/replica/status.rs, components/epaxos/src/replica/test_status.rs, components/epaxos/src/replication/hdlreply.rs, components/epaxos/src/replication/test_hdlreply.rs
- fix: Status should track fast-accept-replies and positive fast-accept-replies separately.
- fix: Status should track accept-replies and positive accept-replies.
=> Fix status

components/epaxos/src/replica/replica.rs, components/epaxos/src/replica/test_replica.rs, components/epaxos/src/replication/hdlreply.rs, components/epaxos/src/replication/test_hdlreply.rs
=> Refactor handle accept replies

components/epaxos/src/replica/errors.rs, components/epaxos/src/replica/exec.rs, components/epaxos/src/replica/replica.rs, components/epaxos/src/replication/errors.rs, components/epaxos/src/replication/hdlreply.rs, components/epaxos/src/replication/replication.rs, components/epaxos/src/replication/test_hdlreply.rs
- And separate sub error StorageError from ReplicaError.
=> Refine error

components/epaxos/src/qpaxos/mod.rs, components/epaxos/src/replica/exec.rs, components/epaxos/src/replica/replica.rs, components/epaxos/src/replication/errors.rs, components/epaxos/src/replication/hdlreply.rs, components/epaxos/src/replication/test_hdlreply.rs
=> Refine errors 2

components/epaxos/Cargo.toml, components/epaxos/src/lib.rs, components/epaxos/src/replica/replica.rs, components/epaxos/src/serverdata/serverdata.rs, components/storage/src/traits.rs, src/server/server.rs, tests/test_replica.rs, tests/test_setget.rs
-   Generics in storage traits does not need to be `Sized`, so that it
is able to accept a `dyn Storage` type.
=> Replica namespace

components/epaxos/src/conf/conf.rs, components/epaxos/src/qpaxos/display.rs, components/epaxos/src/qpaxos/errors.rs, components/epaxos/src/qpaxos/mod.rs, components/epaxos/src/replication/hdlreply.rs, components/epaxos/src/replication/replication.rs, components/epaxos/src/replication/test_hdlreply.rs, components/epaxos/src/serverdata/serverdata.rs, components/epaxos/src/service/service.rs, components/epaxos/src/testutil.rs, components/epaxos/tests/test_repl_server.rs, src/redisapi/redisapi.rs, src/server/server.rs, tests/support/mod.rs, tests/test_replica.rs, tests/test_setget.rs
-   Move predefined test cluster config to mod conf.
There are 2 cluster: az_1 has 1 replica, az_3 has 3 replicas.
-   Tests relies on a cluster use predefined cluster az_1 or az_3.
And removed QPaxosImpl::default().
In tests, checking shared storage changed to checking replica
storage: a `WithNs`, which is Storage with namespace.
-   test: test_set: in a 3-replica cluster it checks fast-accept status
for all 3 replcias.
-   Server adds new_inmem() to create a in-memory cluster for test.
and new_with_server_data() to create a cluster from pre-built
ServerData.
-   let check_repl_common do more common fields check for replies,
includes: instance_id, phase, and stale ballot.
From now on it allows last_ballot to be `None`, for replies from
uninitialized instance has ballot of `None`.
- …
=> Test 3 replica

components/epaxos/src/conf/conf.rs, components/epaxos/src/lib.rs, components/epaxos/src/qpaxos/mod.rs, components/epaxos/src/qpaxos/test_command.rs, components/epaxos/src/serverdata/serverdata.rs, components/epaxos/src/testutil.rs, components/epaxos/src/testutil_cluster.rs, components/epaxos/tests/test_repl_server.rs, src/server/server.rs, tests/support/mod.rs
-   Remove LOCAL_NODE_ID. load node id from cluster config instead.
-   kind() is one of there: NoOp, Get and Set. Delete is a Set kind
command.
-   refactor: rewrite Command::conflict with Command::kind().
-   refactor: test of Command::conflict() with a matrix of expected
confliction.
=> Refine testing

components/epaxos/src/replica/exec.rs, components/epaxos/src/replica/test_exec.rs, components/storage/src/test_engine.rs, components/storage/src/traits.rs, tests/test_replica.rs
=> feat: removes ref:max from storage. A replica does not need to track max-instance-id to work well.

wiki/qpaxos-exec-cn.md
Another exec-algorithm which is more simply to impl.
In this doc it still relies on `seq`, but it is no necessary.
=> doc: exec-algo: version-min-seq
